- hosts: localhost
  vars:
    source_key: "./.ssh/"
    dest_key: "/root/.ssh/"
    personal: "/root/personal"
  become: true
  pre_tasks:
    - name: update cache
      pacman:
        update_cache: true
      tags:
        - install
  tasks:
    - include: task/ssh.yml
    - include: task/basic.yml
    - include: task/zsh.yml
    - include: task/node.yml
    - include: task/nvim.yml
    - include: task/dotfile.yml
